version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./git-repos:/srv/git-repos
